messages:
  not-player: "&cYou are not a player"
  insufficient-permission: "&cInsufficient permission"
  invalid-command: "&cWrong command format"
  invalid-place: "&cYou cant place block here"

mysql:
  host: 'localhost'
  port: 3306
  database: 'minecraft'
  username: 'root'
  password: ''
  tables:
    players: "bwp_players"
    records: "bwp_records"
    types: "bwp_types"

block:
  material: WOOL
  can-placed: SAND

settings:
  material: "REDSTONE_COMPARATOR"
  name: "&2Settings"
  lore:
    - "&9Custom Lore"

mode:
  material: "NETHER_STAR"
  name: "&bMode"
  lore:
    - "&aCustom Lore"

kbc-difficulty:
  material: "REDSTONE_COMPARATOR"
  name: "&2Difficulty"
  lore:
    - "&aCustom Lore"

checkpoint:
  enabled:
    material: "INK_SACK"
    color: LIME
    name: "&7Checkpoint &aEnabled"
    lore:
      - "&aCustom Lore"
  disabled:
    material: "INK_SACK"
    color: GRAY
    name: "&7Checkpoint &cDisabled"
    lore:
      - "&aCustom Lore"

games:
  min-y: 62.5

bridging:
  finish-y: 3 #The number subtracted at the max height (Max Height - Ground Y)
  win:
    title:
      message: "&a{time} secondi"
      fadeIn: 5
      duration: 60
      fadeOut: 20
    message: "&aCompletato! Ci hai messo {time} secondi, con una velocità massima {peekSpeed} m/s"
  loose:
    message: "&cHai fallito! La velocità massima raggiunta è {peekSpeed} m/s"

clutch:
  knockback:
    delay: 2000 #milliseconds
    materials:
      start: IRON_BLOCK
      checkpoint: DIAMOND_BLOCK
    win:
      title:
        message: "&a{time} secondi"
        fadeIn: 5
        duration: 60
        fadeOut: 20
      message: "&aCompletato! Ci hai messo {time} secondi"
      loose:
        message: "&cHai fallito!"
  wall:
    materials:
      block: IRON_BLOCK
      checkpoint: DIAMOND_BLOCK
    win:
      title:
        message: "&a{time} secondi"
        fadeIn: 5
        duration: 60
        fadeOut: 20
      message: "&aCompletato! Ci hai messo {time} secondi"
      loose:
        message: "&cHai fallito!"

launch:
  settings:
    material: "REDSTONE_COMPARATOR"
    name: "&2Impostazioni"
    lore:
      - "&9Scegli TNT o Fireball"
  start-offset: 9 #blocks from spawn
  win:
    title:
      message: "&a{distance} blocchi"
      fadeIn: 5
      duration: 60
      fadeOut: 20
    message: "&aCompletato! Hai percorso {distance} blocchi"
  loose:
      message: "&cHai fallito!"

bedburrow:
  win:
    title:
      message: "&a{distance} blocchi"
      fadeIn: 5
      duration: 60
      fadeOut: 20
    message: "&aCompletato! Hai percorso {distance} blocchi"
  loose:
      message: "&cHai fallito!"